package ui

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/rgrouls/terminal-wrapped/internal/analyzer"
)

// GenerateHTML creates a standalone HTML file with the stats and stories
func GenerateHTML(analysis *analyzer.Analysis, stories map[string]string, cmdRemarks map[string]string, aliasRemarks map[string]string) (string, error) {
	filename := fmt.Sprintf("terminal-wrapped-%s.html", time.Now().Format("20060102-150405"))

	user := os.Getenv("USER")
	if user == "" {
		user = "User"
	}

	html := fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terminal Wrapped 2024 - %s</title>
    <style>
        body {
            background-color: #1a1b26;
            color: #a9b1d6;
            font-family: 'Courier New', Courier, monospace;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
            line-height: 1.6;
        }
        h1, h2, h3 {
            color: #7aa2f7;
            border-bottom: 1px solid #414868;
            padding-bottom: 10px;
        }
        .accent { color: #bb9af7; }
        .muted { color: #565f89; }
        .card {
            background: #24283b;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 30px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.3);
        }
        .story {
            font-style: italic;
            color: #9ece6a;
            margin-bottom: 15px;
            padding: 10px;
            background: #1f2335;
            border-left: 4px solid #9ece6a;
            border-radius: 4px;
        }
        .stat-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 8px;
        }
        .bar-container {
            flex-grow: 1;
            margin-left: 15px;
            background: #414868;
            height: 20px;
            border-radius: 4px;
            overflow: hidden;
        }
        .bar {
            height: 100%%;
            background: linear-gradient(90deg, #7aa2f7, #bb9af7);
        }
        .punchcard {
            display: grid;
            grid-template-columns: 40px repeat(24, 1fr);
            gap: 2px;
            font-size: 10px;
        }
        .pc-cell {
            aspect-ratio: 1;
            border-radius: 2px;
        }
    </style>
</head>
<body>
    <header style="text-align: center; margin-bottom: 50px;">
        <h1 style="border: none; font-size: 2.5em;">🎁 Terminal Wrapped 2024</h1>
        <p>Prepared for <span class="accent">%s</span></p>
        <p class="muted">%d Total Commands • %d Unique</p>
    </header>

    <div class="card">
        <h2>👋 Welcome</h2>
        %s
        <p>You've typed <strong>%d</strong> commands this year. That's a lot of enter keys!</p>
    </div>

    <div class="card">
        <h2>⚡ Terminal Rhythm</h2>
        %s
        <div class="stat-row">
            <span>Most Active Hour</span>
            <span class="accent">%02d:00</span>
        </div>
        <div class="stat-row">
            <span>Most Active Month</span>
            <span class="accent">%s</span>
        </div>
    </div>

    <div class="card">
        <h2>🔥 Coding Streaks</h2>
        %s
        <div class="stat-row">
            <span>Current Streak</span>
            <span class="accent">%d days</span>
        </div>
        <div class="stat-row">
            <span>Longest Streak</span>
            <span class="accent">%d days</span>
        </div>
        <p class="muted" style="text-align: right;">(%s - %s)</p>
    </div>

    <div class="card">
        <h2>🏆 Top Commands</h2>
        %s
        %s
    </div>

    <div class="card">
        <h2>🎭 Top Aliases</h2>
        %s
        %s
    </div>

    <footer style="text-align: center; margin-top: 50px; color: #565f89; font-size: 0.8em;">
        Generated by Terminal Wrapped 🚀
    </footer>
</body>
</html>`,
		user, user, analysis.TotalCommands, analysis.UniqueCommands,
		renderStory(stories, "intro"), analysis.TotalCommands,
		renderStory(stories, "rhythm"), analysis.MostActiveHour, analysis.MostActiveMonth,
		renderStory(stories, "streaks"), analysis.CurrentStreak, analysis.LongestStreak,
		analysis.LongestStreakStart.Format("Jan 02"), analysis.LongestStreakEnd.Format("Jan 02"),
		renderStory(stories, "top_commands"), renderTopCommands(analysis, cmdRemarks),
		renderStory(stories, "aliases"), renderTopAliases(analysis, aliasRemarks),
	)

	err := os.WriteFile(filename, []byte(html), 0644)
	return filename, err
}

func renderStory(stories map[string]string, key string) string {
	if story, ok := stories[key]; ok && story != "" {
		return fmt.Sprintf(`<div class="story">🤖 %s</div>`, story)
	}
	return ""
}

func renderTopCommands(analysis *analyzer.Analysis, remarks map[string]string) string {
	var sb strings.Builder
	maxCount := 0
	if len(analysis.TopCommands) > 0 {
		maxCount = analysis.TopCommands[0].Count
	}

	for _, cmd := range analysis.TopCommands {
		percent := 0.0
		if maxCount > 0 {
			percent = float64(cmd.Count) / float64(maxCount) * 100
		}

		remark := ""
		if r, ok := remarks[cmd.Name]; ok {
			remark = fmt.Sprintf(`<div style="font-size: 0.8em; color: #565f89; font-style: italic; margin-top: 2px;">%s</div>`, r)
		}

		sb.WriteString(fmt.Sprintf(`
        <div class="stat-row" style="align-items: center; margin-bottom: 12px;">
            <span style="width: 80px;">%s</span>
            <div class="bar-container" style="height: 24px;">
                <div class="bar" style="width: %.1f%%;"></div>
            </div>
            <span style="width: 50px; text-align: right;">%d</span>
        </div>
        %s`, cmd.Name, percent, cmd.Count, remark))
	}
	return sb.String()
}

func renderTopAliases(analysis *analyzer.Analysis, remarks map[string]string) string {
	var sb strings.Builder
	maxCount := 0
	if len(analysis.TopAliases) > 0 {
		maxCount = analysis.TopAliases[0].Count
	}

	for _, cmd := range analysis.TopAliases {
		percent := 0.0
		if maxCount > 0 {
			percent = float64(cmd.Count) / float64(maxCount) * 100
		}

		remark := ""
		if r, ok := remarks[cmd.Name]; ok {
			remark = fmt.Sprintf(`<div style="font-size: 0.8em; color: #565f89; font-style: italic; margin-top: 2px;">%s</div>`, r)
		}

		sb.WriteString(fmt.Sprintf(`
        <div class="stat-row" style="align-items: center; margin-bottom: 12px;">
            <span style="width: 80px;">%s</span>
            <div class="bar-container" style="height: 24px;">
                <div class="bar" style="width: %.1f%%;"></div>
            </div>
            <span style="width: 50px; text-align: right;">%d</span>
        </div>
        %s`, cmd.Name, percent, cmd.Count, remark))
	}
	return sb.String()
}
